### ISSUE TITLE
Crash if I try to change settings

### ISSUE THREAD

**Issue by PvtFudgepants** [Faboslav/structurify#1]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

47.3.0

### Mod version information

1.0.0

### Reproduction Steps

Open settings and try to click on either of the 2 config options from the mod config menu.

### Crash Report and latest.log

[latest.log](https://github.com/user-attachments/files/16722115/latest.log)
[crash-2024-08-22_23.41.07-client.txt](https://github.com/user-attachments/files/16722180/crash-2024-08-22_23.41.07-client.txt)

**Comment by Faboslav** [comment]
Hello there, thanks for the report, while the mod worked perfectly in the dev end, i found out that yacl doesnt work with forge in production in its current state, i am not sure what to do in the current state, but i will probably rollback the forge release and keep only the fabric for testing.

**Comment by Faboslav** [comment]
Good news, it should be fixed! https://legacy.curseforge.com/minecraft/mc-mods/structurify/files/5655640, please do let me know.

**Comment by PvtFudgepants** [comment]
Yep! Looks like it's working now. I'm able to change all of the settings without crashes.

**Comment by Faboslav** [comment]
That's great, thanks!
