### ISSUE TITLE
Incompatibility with Dungeons Enhanced Mod

### ISSUE THREAD

**Issue by Beez3-A** [Faboslav/structurify#11]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

Forge 47.3.5

### Mod version information

Structurify 1.0.7 - Dungeons Enhanced 5.2.2

### Expected Behavior

I expected the mods to work together

### Actual Behavior

When using both mods the Dungeon Enhanced structures are spawning under oceans and on top of the water 

Love your mod btw xD

### Reproduction Steps

I'm using the normal performance mods Embeddium and ect. along with sinytra connector and that's all as I tested by removing every mod that isn't performance based.

also using illager warship structure mod and also it cannot find the ship when stucturify is installed

### Screenshots & files

![mods](https://github.com/user-attachments/assets/711d798e-fdbf-4ab2-b544-a4e2ff068482)
![2024-10-09_13 37 37](https://github.com/user-attachments/assets/791d2468-5d8a-4810-bc9d-6c178c86960b)
![2024-10-09_13 38 33](https://github.com/user-attachments/assets/be480fe0-379c-4625-8904-eb3d77aff767)

**Comment by Faboslav** [comment]
Hello, i will try to look into this, sorry for the delay.

**Comment by Faboslav** [comment]
Can you try with 1.0.8 version of the mod please?

**Comment by Vov4ik111** [comment]
> Можете ли вы попробовать версию мода 1.0.8?

Apparently it didn't work(
![image](https://github.com/user-attachments/assets/1ccb2ea9-e29f-4b7a-86fc-64d5e8591680)

**Comment by Faboslav** [comment]
On discord, multiple people confirmed, that the structures now dont spawn in the ocean and other things, weird
