### ISSUE TITLE
Global modifier extra options (feature request)

### ISSUE THREAD

**Issue by Razor235T** [Faboslav/structurify#12]
Hi! I love your mod. I've been using a different one, but then I found yours, and it is very convenient! I set config from config menu on client and then placed config file to my server, all seems to work pretty well.

It could be even more convenient, if a player could change how each structure set or even specific mod behaves to the global modifier (spacing and separation). For example excluding it from being modified by the global modifier parameter or vice versa even more impacted by it. Also, I don't know how difficult it could be, but configuring global modifier separately for every dimension would be cool. Because after setting global modifier I needed to tweak every structure set in every dimension.

**Comment by Faboslav** [comment]
This will be released with the 1.0.9 version of the mod.

**Comment by Faboslav** [comment]
It's released.
