### ISSUE TITLE
[suggestion] Option for 1 structure type per biome.

### ISSUE THREAD

**Issue by Smokedeuch** [Faboslav/structurify#13]
If I am in a plains biome I do not want a second plains village in the same plains biome, but still want it to generate in another plains biome.

**Comment by Faboslav** [comment]
Hello there, this is idea is exactly what would be so great for mc, but sadly in the current terms, its probably impossible to do so

**Comment by Faboslav** [comment]
I am closing this for now as i am just unable to do this kind of thing, sorry.
