### ISSUE TITLE
[Crash] Bunch of mixin errors which cause the config to be broken and causes a crash when joining/creating a world [1.20.1/0.16.2]

### ISSUE THREAD

**Issue by pokesmells** [Faboslav/structurify#3]
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

0.16.2 (Fabric)

### Mod version information

structurify-fabric-mc1.20.1-1.0.2.jar

### Expected Behavior

For mod menu to not lag, and also for there not to be registry and mixin errors

### Actual Behavior

Config is broken and registry/mixin errors

### Reproduction Steps

Download latest version of the mod with a variety of structure mods

### Screenshots & files

https://mclo.gs/0HN8CVD

**Comment by pokesmells** [comment]
https://mclo.gs/B4yvWPm

**Comment by Faboslav** [comment]
Should be fixed with the 1.0.3 release https://github.com/Faboslav/structurify/releases/tag/mc1.20.1-1.0.3.

**Comment by Faboslav** [comment]
Should be fixed by https://github.com/Faboslav/structurify/releases/tag/mc1.20.1-1.0.3
