### ISSUE TITLE
Towns and Towers mod

### ISSUE THREAD

**Issue by maevius669** [Faboslav/structurify#4]
### Minecraft version information

1.21.1

### Mod loader information

Fabric

### Mod loader version information

0.16.3

### Mod version information

1.0.3

### Expected Behavior

load spacing from cristellib's configs

### Actual Behavior

it loads spacing from mod files

### Reproduction Steps

.

### Screenshots & files

so cristellib is required for towns and towers mod but configs created by cristellib for this specific mod wont be read by structurify.
structurify will load data directly from the tnt mod.
on the other hand, configs created by cristellib for minecraft structures will be loaded without problems.
havent checked yet with explorify's structures since when cristellib is installed it will create configs for it as well

**Comment by Faboslav** [comment]
Hello there, i mean loading specific configs from specific mods can and will be an option, but probably later on.

I think that in ideal case this mod should ideally override any other configs, so you can configure everything from one space. It depends on what is needed and wanted, what do you think?

**Comment by maevius669** [comment]
sure one place to configure them all is absolutely great but what i actually meant was to understand how this works.
ok so cristellib's configuration files for all other structure datapacks/mods are overridden,
but then why are the configuration files for minecraft's structures loaded created by cristellib itself ?
![image](https://github.com/user-attachments/assets/8c9e532a-306b-49f4-aa5a-4bb902f2a0bc)
![image](https://github.com/user-attachments/assets/940f5e7c-b9ae-4774-821a-f9b0581c5c5b)

**Comment by Faboslav** [comment]
I probably still dont understand your question, but here is what happens in the backend of my mod, when you open up the config screen or the create world menu my mod simulates same logic what runs when creating the world, it collects all of the acailable datapacks from specific folders and mods, then creates some data based on that and displays it to the user (if in the config), so values that you see should be the values that are and will be probably used in the world while generating the structures. 

But as mentioned in the yellow note, everything can be still different based on other mods implementations.

**Comment by maevius669** [comment]
ok thank you
