### ISSUE TITLE
[Request] Disable structures by dimensions

### ISSUE THREAD

**Issue by Kettle5000** [Faboslav/structurify#7]
I have been trying to find a way to achieve this in forge specifically but mojang has changed structures to be tied to biomes only
since i saw your mod i was wondering if you can achieve this, disabling structures that spawn in the same biome but in a different dimension.

**Comment by Faboslav** [comment]
Hello, what do you mean by that, so for example if there is a plains biome in both overworld and nether, you want to disable the structure in plains, but only in the nether?

**Comment by Kettle5000** [comment]
Yes exactly

**Comment by Faboslav** [comment]
And what structure and biome is this, do you have an example? Its very unusual, and would be very hard to do in terms of this mod

**Comment by Kettle5000** [comment]
i would like to find a way to make it work with all kind of structures (modded and vanilla ones)
Right now im trying to find a way to fix an issue found in the Lost Cities mod
since the dimension uses overworld generation, biomes are the same as overworld, causing structures and features to spawn in.
I tracked down this issue and discovered it was caused because mojang no longer checks dimensions when placing structures, only biomes. I tried to use mixins but the code itself is a big mess that i cant even find a good method to inject code to
thats why i wanted to know if you happen to know a way to achieve this

**Comment by Faboslav** [comment]
I dont think there was a dimension check at any time and point, anyway the lost cities should probably fix a lot of things on their end, for example do an extra conditions on the structure generation for the dimension, or use non overworld biomes.

**Comment by Kettle5000** [comment]
if they were to use non overworld biomes it would defeat the purpose of the dimension being a mirrored version of the overworld
i already got in contact with the creator and we both got to the same problem, and it is how mojang has changed structures 
in 1.12.2 this was not an issue.
anyway since you seem to not find a solution either i get this as closed.

**Comment by Faboslav** [comment]
Yeah, but at the same time adding extra check for dimension on their side should be easy enough
