### ISSUE TITLE
Incompatibility with Alex's Caves

### ISSUE THREAD

**Issue by SeparateBeast68** [Faboslav/structurify#9]
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

Forge - 47.3.1

### Mod version information

1.0.7

### Expected Behavior

Alex's Caves generating Normally. I hope this gets fixed since I want to use it to prevent structures from spawning in Abyssal Chasms because it looks really weird

### Actual Behavior

The Abyssal Chasm doesn't generate and other caves generate like regular caves

### Reproduction Steps

Have Alex's Caves and Structurify downloaded

**Comment by Faboslav** [comment]
Can you try with 1.0.8 version of the mod please?

**Comment by SeparateBeast68** [comment]
So I have been doing some testing and so far everything seams to be working find. I'm happy its working as this mod is so helpful for big modpacks!! Glad I can finally use this mod
